In [ ]:
hello()

def hello():
    print ("hello")

hello()

In [2]:
numbers_list = [1,2,3]
numbers_list = numbers_list * 2
print (numbers_list)

#in a list we can place different data types

mixed_list = [1, "ett", True, 2.3] # dynamic typing in Python
print(mixed_list)
# element in the list is an object, it has information on what type it is
# this requires some overhead, which slows down the program
# note that when we have one data type, it is unnessesary to have this overhead 

[1, 2, 3, 1, 2, 3]
[1, 'ett', True, 2.3]


In [6]:
# in numpy we have statically typed

import numpy as np

#create an array from a list

vector1 = np.array([2,5,1])
print(vector1)

# elementwice multiplication
vector2 = vector1*2
print(vector2)

print(f"{vector1+2}")

#indexing

print(f"{vector1[2]=}")
print(f"{vector1[-1]=}")
#slicing
print(f"{vector1[1]=}")

vector1[1] = 1337
print(vector1)

# can't append to an array - can't change its size
# can't have different types in an array

# sort

vector1.sort()
print(f"{vector1=}")

# sum

print(f"{vector1.sum()=}")
print(f"{vector1.mean()=:.2f}")



[2 5 1]
[ 4 10  2]
[4 7 3]
vector1[2]=1
vector1[-1]=1
vector1[1]=5
[   2 1337    1]
vector1=array([   1,    2, 1337])


In [12]:
ones_vector = np.ones((10))
print(f"{ones_vector=}")

#2d array of shape
matrix_3_3 = np.ones((3,3))
print(f"{matrix_3_3=}")

# [row, index] - counts from 0
matrix_3_3[2,1] = 10

matrix_3_3

ones_vector=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
matrix_3_3=array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1., 10.,  1.]])

In [13]:
np.zeros((2,5)) # shapelike - takes in tuple or a list

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
print(matrix_3_3.shape)
matrix_3_3[2,:]

# slicing operator to get a row
print(f"{matrix_3_3[2,:]=}")

# slicing operator to get a column
print(f"{matrix_3_3[:,1]=}")

# add 2 vectors
matrix_3_3[2,:] + matrix_3_3[:,1]


(3, 3)
matrix_3_3[2,:]=array([ 1., 10.,  1.])
matrix_3_3[:,1]=array([ 1.,  1., 10.])


array([ 2., 11., 11.])